env:
  global:
  - CONAN_REFERENCE: FinSec.Poco/1.9.0
  - CONAN_USERNAME: finsecadmin
  - CONAN_LOGIN_USERNAME: finsecadmin
  - CONAN_CHANNEL: testing
  - CONAN_UPLOAD: https://api.bintray.com/conan/finsecsystem/finsec.pocoproject
  - CONAN_STABLE_BRANCH_PATTERN: release/*
  - CONAN_TOTAL_PAGES: 4
  - CONAN_UPLOAD_ONLY_WHEN_STABLE: 1
linux:
  os: linux
  sudo: required
  language: python
  python: '3.6'
  services: &1
  - docker
osx:
  os: osx
  language: generic
matrix:
  include:
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=lasote/conangcc7 CONAN_CURRENT_PAGE=1
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=lasote/conangcc7 CONAN_CURRENT_PAGE=2
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=lasote/conangcc7 CONAN_CURRENT_PAGE=3
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=7 CONAN_DOCKER_IMAGE=lasote/conangcc7 CONAN_CURRENT_PAGE=4
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc6 CONAN_CURRENT_PAGE=1
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc6 CONAN_CURRENT_PAGE=2
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc6 CONAN_CURRENT_PAGE=3
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=6 CONAN_DOCKER_IMAGE=lasote/conangcc6 CONAN_CURRENT_PAGE=4
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc5 CONAN_CURRENT_PAGE=1
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc5 CONAN_CURRENT_PAGE=2
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc5 CONAN_CURRENT_PAGE=3
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=5 CONAN_DOCKER_IMAGE=lasote/conangcc5 CONAN_CURRENT_PAGE=4    
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49 CONAN_CURRENT_PAGE=1
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49 CONAN_CURRENT_PAGE=2
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49 CONAN_CURRENT_PAGE=3
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_GCC_VERSIONS=4.9 CONAN_DOCKER_IMAGE=lasote/conangcc49 CONAN_CURRENT_PAGE=4
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40 CONAN_CURRENT_PAGE=1
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40 CONAN_CURRENT_PAGE=2
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40 CONAN_CURRENT_PAGE=3
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_CLANG_VERSIONS=4.0 CONAN_DOCKER_IMAGE=lasote/conanclang40 CONAN_CURRENT_PAGE=4
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39 CONAN_CURRENT_PAGE=1
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39 CONAN_CURRENT_PAGE=2
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39 CONAN_CURRENT_PAGE=3
  - os: linux
    sudo: required
    language: python
    python: '3.6'
    services: *1
    env: CONAN_CLANG_VERSIONS=3.9 CONAN_DOCKER_IMAGE=lasote/conanclang39 CONAN_CURRENT_PAGE=4
  - os: osx
    language: generic
    osx_image: xcode9
    env: CONAN_APPLE_CLANG_VERSIONS=9.0 CONAN_CURRENT_PAGE=1
  - os: osx
    language: generic
    osx_image: xcode9
    env: CONAN_APPLE_CLANG_VERSIONS=9.0 CONAN_CURRENT_PAGE=2
  - os: osx
    language: generic
    osx_image: xcode9
    env: CONAN_APPLE_CLANG_VERSIONS=9.0 CONAN_CURRENT_PAGE=3
  - os: osx
    language: generic
    osx_image: xcode9
    env: CONAN_APPLE_CLANG_VERSIONS=9.0 CONAN_CURRENT_PAGE=4
  - os: osx
    language: generic
    osx_image: xcode8.3
    env: CONAN_APPLE_CLANG_VERSIONS=8.1 CONAN_CURRENT_PAGE=1
  - os: osx
    language: generic
    osx_image: xcode8.3
    env: CONAN_APPLE_CLANG_VERSIONS=8.1 CONAN_CURRENT_PAGE=2
  - os: osx
    language: generic
    osx_image: xcode8.3
    env: CONAN_APPLE_CLANG_VERSIONS=8.1 CONAN_CURRENT_PAGE=3
  - os: osx
    language: generic
    osx_image: xcode8.3
    env: CONAN_APPLE_CLANG_VERSIONS=8.1 CONAN_CURRENT_PAGE=4    
  - os: osx
    language: generic
    osx_image: xcode7.3
    env: CONAN_APPLE_CLANG_VERSIONS=7.3 CONAN_CURRENT_PAGE=1
  - os: osx
    language: generic
    osx_image: xcode7.3
    env: CONAN_APPLE_CLANG_VERSIONS=7.3 CONAN_CURRENT_PAGE=2
  - os: osx
    language: generic
    osx_image: xcode7.3
    env: CONAN_APPLE_CLANG_VERSIONS=7.3 CONAN_CURRENT_PAGE=3
  - os: osx
    language: generic
    osx_image: xcode7.3
    env: CONAN_APPLE_CLANG_VERSIONS=7.3 CONAN_CURRENT_PAGE=4

install:
- chmod +x .travis/install.sh
- "./.travis/install.sh"
script:
- chmod +x .travis/run.sh
- "./.travis/run.sh"
